### ISSUE TITLE
Import mit Contao Manager

### ISSUE THREAD

**Issue by jankout** [inspiredminds/contao-wordpressimport#1]
Hallo, 

wie geht kann man den Import mit der Installation über Contao-Manager starten? Leider steht mir  keine Möglichkeit zur Verfügung, Konsole zu nutzen. Danke. 

Liebe Grüße,

J.

**Comment by fritzmg** [comment]
Über den Contao Manager geht das nicht. Dazu müsstest du einen Feature Request [hier](https://github.com/contao/contao-manager/issues) machen, damit man beliebige Kommandos als Konsolen Task über den Contao Manager starten kann.

Du hast aber die Möglichkeit den Import (periodisch) über den Cronjob zu machen. Siehe die [README](https://github.com/inspiredminds/contao-wordpressimport/blob/master/README.md):

> Import periodically: Instead of importing the WordPress posts via console command (see below), you can activate a periodic import here, which will be done via Contao's cronjob.
>
> …
>
>  ### Periodic import
>
> If you activated the periodic import, the WordPress posts will be imported hourly by Contao's cronjob.
>
> _Note:_ by default only 10 items will be imported with each cronjob execution. The import can take a long time (depending on the number of WordPress posts and the number of images to be downloaded). This limit is there so that a cronjob execution does not block a user's request for a long time (or at least until the max_execution_time limit is hit). You can change this limit in the System Settings.
