### ISSUE TITLE
Problem mit Blog-Verzeichnis

### ISSUE THREAD

**Issue by paha77** [inspiredminds/contao-wordpressimport#2]
Wenn der importierende Blog in einem Unterverzeichnis ist (z.B. /blog/), funktioniert das Tool nicht, weil im Importer.php die API Endpoints absolut sind.

```php
/**
* API endpoint for posts
*/
const API_POSTS = "/wp-json/wp/v2/posts";
```

Ich könnte einen Pull-Request vorbereiten, falls es notwendig wird.

**Comment by fritzmg** [comment]
In so einem Fall musst du die Wordpress Import URL einfach _mit_ Unterverzeichnis angeben, das sollte ohne Probleme funktionieren.

**Comment by paha77** [comment]
Bei mir geht das mit dem Unterverzeichnis auch nicht, egal ob ich /blog oder /blog/ angebe.  Ich vermute, dass es so ist, weil der GuzzleHttp\Client den "/wp-json/wp/v2/posts" wie ein echter Browser "übersetzt":

![grafik](https://user-images.githubusercontent.com/5096366/42453676-c3083de2-838d-11e8-9613-dcbb12435c84.png)

![grafik](https://user-images.githubusercontent.com/5096366/42453757-0320e94c-838e-11e8-9a40-14492c2a5be3.png)

![grafik](https://user-images.githubusercontent.com/5096366/42453746-f5039c88-838d-11e8-8608-775bb00919ad.png)

![grafik](https://user-images.githubusercontent.com/5096366/42453757-0320e94c-838e-11e8-9a40-14492c2a5be3.png)

**Comment by paha77** [comment]
Aber wenn ich die Endpoints so umschreibe, geht alles gut, obwohl es selbstverständlich keine vollständige Lösung ist:

```php
    /**
     * API endpoint for posts
     */
    const API_POSTS = "wp-json/wp/v2/posts";

    /**
     * API endpoint for categories
     */
    const API_CATEGORIES = "wp-json/wp/v2/categories";

    /**
     * API endpoint for users (authors)
     */
    const API_USERS = "wp-json/wp/v2/users";

    /**
     * API endpoint for media (images)
     */
    const API_MEDIA = "wp-json/wp/v2/media";

    /**
     * API endpoint for comments
     */
    const API_COMMENTS = "wp-json/wp/v2/comments";
```

**Comment by fritzmg** [comment]
Doch, das wäre die korrekte Lösung :)

**Comment by paha77** [comment]
Na ja, wenn der GuzzleHttp\Client den URL richtig handelt, funktioniert es gut, egal ob der Blog-URL mit oder ohne / definiert ist.

**Comment by fritzmg** [comment]
Genau, so ist es ja auch vorgesehen: http://docs.guzzlephp.org/en/stable/quickstart.html
Wenn die base uri einen trailing slash und die request uri keinen leading slash hat, dann wird der request relativ zur gesamten base uri durchgeführt. So sollte es auch innerhalb der Extension implementiert werden.

Man müsste jedoch sicherstellen, dass die base uri immer einen trailing slash hat.

**Comment by paha77** [comment]
Ja, deswegen meinte ich, dass mein Lösungvorschlag nicht vollständig war.  Soll ich eine Pull Request mit dem Trailing Slash-Check machen?

**Comment by fritzmg** [comment]
Ja, wobei ich einfach [hier](https://github.com/inspiredminds/contao-wordpressimport/blob/master/src/WordPressImportBundle/Service/Importer.php#L115) bzw. vorher überprüfen würde, ob ein trailing slash da ist, und wenn nicht, einen anhängen. Muss nicht bei der Eingabe überprüft werden imho.

**Comment by fritzmg** [comment]
Closed in favor of #3
