### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by johannes-bittner** [inspiredminds/contao-wordpressimport#8]
Contao 4.13, PHP 8.0 / 8.1 on shared hosting with Let's Encrypt certificates shows the following error (tried on different hosting platforms, but all with Let's Encrypt certificates): 

> An error occurred while importing WordPress posts: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://www.my-wp-source.de/wp-json/wp/v2/posts?per_page=10&offset=0)

From what I understand, this is because cURL can't find the certificate on the local installation, not on the WordPress installation where it is supposed to copy the postings; has anyone else experienced this or found a solution?

**Comment by fritzmg** [comment]
From where to where exactly are you trying to import?

**Comment by johannes-bittner** [comment]
I am trying to import WordPress posts from a remote WordPress installation (https://www.eucor-uni.org) to my Contao installation (Contao 4.13, PHP 8.1) like in the usage description. The remote installation uses WP 6.1 and has the REST API enabled.

**Comment by fritzmg** [comment]
This is an issue with your local setup then. See https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate for example.

**Comment by johannes-bittner** [comment]
Yes, that's why I wrote: 

> From what I understand, this is because cURL can't find the certificate on the local installation, not on the WordPress installation where it is supposed to copy the postings; 

And that's why I was asking: 

> has anyone else experienced this or found a solution?

Because the possibilities to go around this are probably limited on a shared hosting and because I think that I might not be the only one using Let's Encrypt certs. Just in case somebody has made a similar experience and maybe a solution.

**Comment by fritzmg** [comment]
> Because the possibilities to go around this are probably limited on a shared hosting

It's an issue with your local setup, not with the hosting environment.
